### ISSUE TITLE
hi. can you upload the step files ?

### ISSUE THREAD

**Issue by rippschemitkraut** [mjbots/moteus#1]
hi. can you upload the step files ?
thx.

**Comment by jpieper** [comment]
Thanks for you interest!  At the moment, the CAD files that are currently uploaded (F360 exports from an indeterminate point in the past), is all you're going to get.

**Comment by jpieper** [comment]
I suppose if there is some specific model you'd like in STEP format, let me know and your email address, and I can export it for you from Fusion.

**Comment by jpieper** [comment]
Closing this after no feedback for a week.

**Comment by rippschemitkraut** [comment]
hi, didnt see this email. my email is shellbomber@gmail.com -   thx anyway

Am Di., 28. Apr. 2020 um 19:01 Uhr schrieb jpieper <notifications@github.com
