### ISSUE TITLE
tview scaling issue after removing plot

### ISSUE THREAD

**Issue by xninop** [mjbots/moteus#12]
Using a moteus developer's kit, in tview, I am seeing some weird behaviour that I have been able to recreate. If you choose to plot, let's say, unwrapped_position from servo_stats, and send it to plot left, then send filt_fet_temp_C, for example, to plot right, wait a bit then "remove" the first stat from the display area, the visible window of the remaining plot gets smaller and smaller and the x-axis coordinates sometimes even jump around, I've seen, becoming negative, if you wait long enough. The "old" plotted values start getting erased from the left when the plot reaches about 1/4 of the grid from the left until the remaining visible plot is bunched up at the right of the display area.

**Comment by jpieper** [comment]
Note, you can work around this by adding any plot to the left axis again.  i.e. once you've used an axis, always use the axis.  This is a bug in matplotlib, I'll look to see if there is some way to work around it.  removing things is only kinda supported there already.
