### ISSUE TITLE
Getting started does not explain how to calibrate the controller

### ISSUE THREAD

**Issue by Nate711** [mjbots/moteus#14]
Am I missing something or does the getting started guide not explain how to calibrate the controller? Thanks. https://github.com/mjbots/moteus/blob/main/docs/getting_started.md

**Comment by jpieper** [comment]
The getting started guide is aimed at the devkit, which comes calibrated from the factory.

**Comment by jpieper** [comment]
I did add a reference in ef86e2a506ff27af017b6f994941b36b6b1abafe
