### ISSUE TITLE
Chaging Id permanent

### ISSUE THREAD

**Issue by ALxander19** [mjbots/moteus#27]
In your documentation I don't find how to change the id permanently. Thanks in advance!

**Comment by jpieper** [comment]
You first reconnect with the new id, then issue the `conf write` command per: https://github.com/mjbots/moteus/blob/main/docs/reference.md#idid

**Comment by ALxander19** [comment]
You have to do it until you see the ok message. Most of the times that message don't show.

**Comment by jpieper** [comment]
Yep, if you don't see the `OK` it didn't work.  However, you shouldn't have to do it multiple times, just once after reconnecting with the new ID.
