### ISSUE TITLE
Direct torque control with python

### ISSUE THREAD

**Issue by iseeag** [mjbots/moteus#29]
Been experimenting using python lately. I wonder the best way to torque control the motor, so by looking at the reference, if I want to set torque to 0.8, I should do this:
```
...
    state = await c.set_position(feedforward_torque=0.8,
                                 kp_scale=0,
                                 kd_scale=0,
                                 query=True)
...
```
Is this even correct?  Thanks!

**Comment by jpieper** [comment]
Yes, that command a torque of 0.8Nm.  Do note that with the register protocol, there is by default a watchdog timeout that requires you send that command repeatedly at least every 100ms or the controller will enter a fault state: https://github.com/mjbots/moteus/blob/main/docs/reference.md#servodefault_timeout_s

**Comment by jpieper** [comment]
I'll consider this resolved.

**Comment by iseeag** [comment]
Thanks heaps!
