### ISSUE TITLE
Tview: unexpected keyword argument

### ISSUE THREAD

**Issue by Fergus-MW** [mjbots/moteus#32]
Freshly installed tview using pip, getting this error everytime and can't interact with motor controller.
![image](https://user-images.githubusercontent.com/6226474/177570252-0c3718ba-d24e-472f-bce2-603c445d2002.png)

**Comment by jpieper** [comment]
You need to upgrade your `moteus` library, it seems the pip version requirements aren't completely correct.

If you installed them in your user account, it would be `pip3 install --upgrade moteus`  if as root it would be `sudo pip3 install --upgrade moteus`

**Comment by Fergus-MW** [comment]
Updated moteus from 0.3.16 to 0.3.42 and that fixed it. Thanks for the fast reply!

**Comment by jpieper** [comment]
No problem!

**Comment by jpieper** [comment]
For good measure: https://github.com/mjbots/moteus/commit/9e0758333c190a2a73538bcc91ca479d91e8da34
