### ISSUE TITLE
Motor position going out of range even if motor is held in place

### ISSUE THREAD

**Issue by kibidev** [mjbots/moteus#37]
Holding a motor in place (at e.g. position ~0) will still stop as at position servopos.position_min/max after a while when a velocity is set.
This is tested in velocity mode (setting kp=0, ki=0).

Running attached code with motor unobstructed will case position limit to be reached after ~10 seconds, and motor will stop (expected behavior).
When obstructing the motor and running the code, the motor will still stop after ~10s, reported position will stay at ~0 the entire time.

There seems to be some sort of internal state/calculated position that triggers position limits as well.
Is this intentional?
Can it be disabled somehow?

```
import moteus
import asyncio
import math

async def run():
    controller = moteus.Controller()
    stream = moteus.Stream(controller)
    await controller.set_stop()
    await controller.set_rezero()
    await stream.command(b'conf set servopos.position_min -10.0')
    await stream.command(b'conf set servopos.position_max 10.0')

    await stream.command(b'conf set servo.default_accel_limit 5.0')

    await stream.command(b'conf set servo.max_velocity 7.0')
    await stream.command(b'conf set servo.default_velocity_limit 5.0f')

    # Velocity control
    await stream.command(b'conf set servo.pid_position.kd 0.2')

    # Deactivate position controller
    await stream.command(b'conf set servo.pid_position.kp 0.0')
    await stream.command(b'conf set servo.pid_position.ki 0.0')
    await stream.command(b'conf set servo.pid_position.ilimit 0.0')
    await stream.command(b'conf set servo.pid_position.iratelimit 0.0')

    while True:
        telemetry = await controller.set_position(position=math.nan,
                                            stop_position=math.nan,
                                            velocity=1.0,
                                            maximum_torque=0.2,
                                            query=True)
        print(telemetry)

asyncio.run(run())
```

**Comment by kibidev** [comment]
Tested with FW versions:
20220501-moteus-0965b28edd417f4e935f87d1ad40a607093d816f.elf
20220730-moteus-75df0139aaf6e76f207dffae17b81b39f3d5d5ce.elf
20220803-moteus-26e636ddb36b702a361291b0ab842acd881f281b.elf

Tested on HW model 800 and 700.

**Comment by jpieper** [comment]
If you have the `kp` term set to 0, then setting `servo.max_position_slip` to 0 will have no other effect.  However, the combination of those two means that the velocity control has no effective integrative term, and in steady state the velocity will never match the control velocity in the presence of an external torque.  If you need the velocity to track accurately, you should use non-zero values for both.  The `kp` will control the "velocity integrative term", and the `max_position_slip` will control the integrator windup limit.

**Comment by kibidev** [comment]
Great, thanks again.
Accurate velocity is not important in our application, so it should be good like this.

**Comment by jpieper** [comment]
Great, I'll close this out then.  Come back if you have more questions, or join the mjbots discord!  https://discord.gg/W4hUpBb
