### ISSUE TITLE
Suggestion - Enable Discussions / Query over EtherCat

### ISSUE THREAD

**Issue by grbd** [mjbots/moteus#39]
Hi,
I was wondering if it might be an idea to enable discussions in the github settings for the repo?

Also I was wondering if there had been any thoughts on the use of EtherCat?
There's the Trinamic TMC8462A-BA which is a BGA part
It seems to be around only £20 or so it would be interesting if this could be integrated into the Moteus
(especially now that ODrive has gone closed source)
maybe as an addon board.

  * https://www.farnell.com/datasheets/3119187.pdf
  * https://www.farnell.com/datasheets/3119187.pdfhttps://www.trinamic.com/fileadmin/assets/Products/Eval_Documents/TMC8462-EVAL_user_manual_rev1.00.pdf

**Comment by jpieper** [comment]
Hi and thanks for your interest!

At the moment, despite it not being ideal for all types of interaction, I'm trying to keep design discussions and such in the mjbots Discord: https://discord.gg/W4hUpBb

And no, there are no plans within mjbots to support EtherCat.  As you noted, the design is open source, so you are free to modify it to add support yourself!

**Comment by grbd** [comment]
Ok
