### ISSUE TITLE
MAX15062AATA+T in the n1 circuit should rather be MAX15062BATA+T

### ISSUE THREAD

**Issue by Fellfalla** [mjbots/moteus#40]
The label of the 5V voltage supply in the n1 .sch seems to be erroneously still the converter of the r4.11 version.

Change MAX15062AATA+T -> MAX15062BATA+T

**Comment by jpieper** [comment]
Thanks!  I'll get this or something similar merged.  FYI, the eagle `MPN` attribute is the source of truth for part selection.  Everything else has risks of being lies.

**Comment by jpieper** [comment]
Fixed in: dc715007c683322852fb92333ad146a01155c14e
