### ISSUE TITLE
modify the communication mode (FDCAN to classic CAN )

### ISSUE THREAD

**Issue by MaxKingWealth** [mjbots/moteus#44]
What I mean is can we modify the communication mode of FDCAN to classic CAN communication by unpacking and packing the communication protocol

**Comment by jpieper** [comment]
The answer is that there is no easy way to use moteus with CAN 2.0.

If you want to have a more detailed design discussion, it may be easier to converse in the mjbots discord: https://discord.gg/W4hUpBb
