### ISSUE TITLE
Use hardware trigger for ADCs

### ISSUE THREAD

**Issue by qosch** [mjbots/moteus#48]
I read your blog post on the STM32G4s ADC issue. Great work!
Did I get that right, that triggering the ADCs at exactly the same time would fix the issue?
In that case, there are hardware connections that can be used to trigger ADCs from timer update events (or some other timer events ). See Reference Manual Chapter 11.3.2, 21.4.18 and 28.3.31.

**Comment by jpieper** [comment]
I did implement a hardware trigger based fix, but didn't deploy it because the current software fix was easier to manage and as effective so am sticking with it for now: 4db361035ac5adc999769b530727a5067b6d457b
