### ISSUE TITLE
can moteus run on a MIT  compatible  hardware

### ISSUE THREAD

**Issue by yushun06** [mjbots/moteus#52]
I bought a MIT compatible motor which could run directly on https://github.com/bgkatz/motorcontrol. 

I think moteus use the same chips such as 5027p, drv8323, stm32.

Can i just modify some pin def and use moteus on this hardware?

**Comment by jpieper** [comment]
Sadly no.  moteus relies on the features of the STM32G4 controller, which is not compatible with the chips used on Ben Katz controllers.
