### ISSUE TITLE
Moteus R4.11 uses a linear incremental encoder to control the timing timeout of linear motor calibration

### ISSUE THREAD

**Issue by away12356** [mjbots/moteus#62]
@jpieper

**Comment by jpieper** [comment]
moteus does not currently support linear motors at all.

Is this a feature request?

**Comment by away12356** [comment]
Can it only be used for rotating motors？

**Comment by jpieper** [comment]
Correct, only rotating motors.

The firmware and tools are open source, so you could implement support yourself.  If you did so, you would certainly be welcome to share any results back, but it isn't required.

**Comment by away12356** [comment]
Hi Josh,
How to use the can send command? Display ERR unknown command on tview
![Uploading 屏幕截图 2024-07-25 105910.png…]()

**Comment by away12356** [comment]
![屏幕截图 2024-07-25 105910](https://github.com/user-attachments/assets/b1433654-0f58-4333-907f-cfeaf8dc251c)

**Comment by away12356** [comment]
![屏幕截图 2024-07-25 105910](https://github.com/user-attachments/assets/93cdc91e-a9bd-487d-a65e-6e0db5c5bd88)

**Comment by away12356** [comment]
@jpieper
