### ISSUE TITLE
How to use the can send command? Display ERR unknown command on tview

### ISSUE THREAD

**Issue by away12356** [mjbots/moteus#63]
![屏幕截图 2024-07-25 105910](https://github.com/user-attachments/assets/5c23ee3e-42bf-4c53-99e1-1a6efafcecfe)

**Comment by jpieper** [comment]
I'll assume you were able to make this work.

**Comment by away12356** [comment]
What command is sending the original CAN from POS 1 0 nan v1 a1

**Comment by away12356** [comment]
What command is sent in the original CAN from POS 1 0 nan v1 a1?
