### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Chetanyadav03** [mjbots/moteus#66]
while running the moteus BLDC motor with the r4.11 controllor(moteus), the calibration process showed an error for runtime, saying the firmware doesnot support the direction of the Motor. The exact error is:
RuntimeError: Requested motor direction not possible with current firmware version
What can be done to remove this error, it worked few hours earlier, but stopped working as i updated my windows

**Comment by jpieper** [comment]
You can additionally pass `--cal-invert` to the calibration command or upgrade the firmware of your moteus.

**Comment by Chetanyadav03** [comment]
Can u please guide on how to upgrade the firmware for the moteus controller

**Comment by jpieper** [comment]
https://github.com/mjbots/moteus/blob/main/docs/reference.md#flashing-over-can

**Comment by jpieper** [comment]
Was that enough to get your firmware updated?

Note, that passing `--cal-invert` is an equally fine option.

**Comment by Chetanyadav03** [comment]
Yes it worked... Thanks a lot for your help... Before this I wasted like 3
hrs trying to rectify it but after your help it took about 10 minutes ...
👍🏼

**Comment by jpieper** [comment]
Great!
