### ISSUE TITLE
What command is sent in the original CAN from POS 1 0 nan v1 a1?

### ISSUE THREAD

**Issue by away12356** [mjbots/moteus#67]

**Comment by away12356** [comment]
Thank you very much, the problem has been resolved

**Comment by away12356** [comment]
Hello, how to solve timeout after running

**Comment by jpieper** [comment]
You can clear faults by sending a stop command.

To avoid the fault in the first place, you can either send commands faster than the configured watchdog timeout:

https://github.com/mjbots/moteus/blob/main/docs/reference.md#servodefault_timeout_s

Or change or disable the timeout.

**Comment by jpieper** [comment]
I'm going to mark this as closed now since there seem to be no further questions.
