### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'   what():  Unable to find a default transport: fdcanusb: Operation not supported The program has unexpectedly finished.

### ISSUE THREAD

**Issue by away12356** [mjbots/moteus#72]

**Comment by jpieper** [comment]
That means the C++ library was unable to open the fdcanusb.  Are you able to use the python library or tools that use it like `moteus_tool`?  You may have to use `strace` to identify what exact error was returned.

**Comment by jpieper** [comment]
I'm assuming this has been resolved as there was no followup.
