### ISSUE TITLE
drv8323

### ISSUE THREAD

**Issue by away12356** [mjbots/moteus#73]
![捕获](https://github.com/user-attachments/assets/475a4d9d-7e38-4c09-a85b-526d654220e6)

**Comment by jpieper** [comment]
The uvlo fault indicates an undervoltage on the input. That can happen if moteus draws more power than your supply can provide.

**Comment by jpieper** [comment]
If you need to operate with a constrained supply, you can always configure the `servo.max_power_W` to be lower.  Note that you may also need to then lower `servo.default_accel_limit` so that the velocity control loop continues to track well.

**Comment by away12356** [comment]
Is there a command for relative position

**Comment by away12356** [comment]
I want to turn 120 degrees in the previous position

**Comment by jpieper** [comment]
There is not a single command.  You can either:

1. Query the position, add 0.33333 to it, then send that command.

2. Force the reported position to 0 then command 0.33333, like:

```
d exact 0
d pos 0.33333 0 nan
```

**Comment by away12356** [comment]
thank you
