### ISSUE TITLE
Can't the resolution of Moteus using incremental encoders exceed 200000

### ISSUE THREAD

**Issue by away12356** [mjbots/moteus#76]

**Comment by jpieper** [comment]
Are you observing an unexpected behavior?  If so, please describe it.

**Comment by away12356** [comment]
Manually rotate the motor quickly, with no change in CPR and a large amount of error data

**Comment by away12356** [comment]
R11, I am using software orthogonal. How can I connect hardware orthogonal

**Comment by jpieper** [comment]
With software quadrature, you are limited to roughly 100000 counts per second of motion, no matter what the resolution is. 

Unfortunately, hardware quadrature is not supported on moteus-r4, only on moteus-c1 and moteus-n1.  With those boards and hardware quadrature, the limit is higher at roughly 10000000 counts per second.

**Comment by away12356** [comment]
What is the difference between hardware orthogonality and software orthogonality

**Comment by jpieper** [comment]
Software quadrature is implemented as a software interrupt, hardware quadrature uses a dedicated hardware decoder in the microcontroller.

**Comment by away12356** [comment]
Is hardware orthogonal wiring the same as software orthogonal wiring

**Comment by away12356** [comment]
硬件正交布线与软件正交布线相同吗？

**Comment by away12356** [comment]
Hardware quadrature wiring is the same as software quadrature?
