### ISSUE TITLE
Missing python source distributions for moteus >= 0.3.73

### ISSUE THREAD

**Issue by g0hl1n** [mjbots/moteus#77]
Hi,
first of all thanks for providing moteus itself and for keeping it at such an excellent quality!
I'm integrating the moteus python package in an OpenEmbedded built system and it basically works like a charm.

Nonetheless when updating to moteus >= [0.3.73](https://pypi.org/project/moteus/0.3.73) the build system (bitbake) was unable to fetch the source distribution from files.pythonhosted.org.
After looking around the pypi.org project page and the different releases it seems there is no source distribution provided since version 0.3.73.

[0.3.72](https://pypi.org/project/moteus/0.3.72/#files) still provides the source distribution file and https://files.pythonhosted.org/packages/source/m/moteus/moteus-0.3.72.tar.gz is available.

Therefore I wanted to ask if it would be possible to provide the source distribution files on pypi.org/pythonhosted.org again, or if there's a reason behind removing it?

Thanks a lot!
@g0hl1n

**Comment by jpieper** [comment]
Sorry!  I had assumed that since both of those wheels are pure python, there weren't any use cases for the source distribution.  I've uploaded 0.3.76 now and will do so going forward for future releases.

Good luck!
